title = "Centralized logging with CDK workshp"
#googleAnalytics = "UA-174210693-1"
languageCode = "ko-KR"
defaultContentLanguage = "ko"

theme = "learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
uglyurls = true
relativeURLs=true
CanonifyURLs=true
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

baseURL = "https://main.d1xohcr6zze1hs.amplifyapp.com/"
#baseURL = "http://localhost:1313/"


[params]
  author = "Dongmin Lee"
  description = "Centralized logging with CDK workshop"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> CDK workshop"
  url = "https://cdkworkshop.com/"
  weight = 1000
[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> CDK Roadmap"
  url = "https://github.com/orgs/aws/projects/7"
  weight = 1010

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Base project repo"
  url = "https://github.com/reoim/centralized-logging-skeleton.git"
  weight = 1040

[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"

